<div class="container">
    <div class="mt-3 mb-3">
        <div class="card">
            <div class="card-body">
                <h3>Výuka fotografování</h3>
                <p><b>Karolína Malá</b></p>
                <p>Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Aliquam erat volutpat. Praesent id justo in neque elementum ultrices. Phasellus enim erat,
                    vestibulum vel, aliquam a, posuere eu, velit. Temporibus autem quibusdam et aut officiis debitis aut rerum necessitatibus saepe eveniet ut et voluptates
                    repudiandae sint et molestiae non recusandae.</p>
                <a href="<?= HOME_PATH ?>/demand/1">zobrazit více</a>
            </div>
        </div>
    </div>
    <div class="mt-3 mb-3">
        <div class="card">
            <div class="card-body">
                <h3>Hledám učitele fyziky</h3>
                <p><b>Karolína Malá</b></p>
                <p>Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Aliquam erat volutpat. Praesent id justo in neque elementum ultrices. Phasellus enim erat,
                    vestibulum vel, aliquam a, posuere eu, velit. Temporibus autem quibusdam et aut officiis debitis aut rerum necessitatibus saepe eveniet ut et voluptates
                    repudiandae sint et molestiae non recusandae.</p>
                <a href="<?= HOME_PATH ?>/demand/1">zobrazit více</a>
            </div>
        </div>
    </div>
    <div class="mt-3 mb-3">
        <div class="card">
            <div class="card-body">
                <h3>Fitness trenér v Brně</h3>
                <p><b>Karolína Malá</b></p>
                <p>Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Aliquam erat volutpat. Praesent id justo in neque elementum ultrices. Phasellus enim erat,
                    vestibulum vel, aliquam a, posuere eu, velit. Temporibus autem quibusdam et aut officiis debitis aut rerum necessitatibus saepe eveniet ut et voluptates
                    repudiandae sint et molestiae non recusandae.</p>
                <a href="<?= HOME_PATH ?>/demand/1">zobrazit více</a>
            </div>
        </div>
    </div>
    <div class="mt-3 mb-3">
        <div class="card">
            <div class="card-body">
                <h3>Výuka v programu Adobe Photoshop</h3>
                <p><b>Karolína Malá</b></p>
                <p>Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Aliquam erat volutpat. Praesent id justo in neque elementum ultrices. Phasellus enim erat,
                    vestibulum vel, aliquam a, posuere eu, velit. Temporibus autem quibusdam et aut officiis debitis aut rerum necessitatibus saepe eveniet ut et voluptates
                    repudiandae sint et molestiae non recusandae.</p>
                <a href="<?= HOME_PATH ?>/demand/1">zobrazit více</a>
            </div>
        </div>
    </div>
</div>