<div class="container">
    <form method="POST">
        <label for="heading">Zadejte nadpis</label><br>
        <input type="text" name="heading" id=""><br>

        <label for="photo">Nahrajte ilustrační foto</label><br>
        <input type="file" name="photo" id=""><br>

        <label for="category">Zaraďte vyučování do kategorie</label><br>
        <select name="category" id="">
            <option value="Sport">Sport</option>
            <option value="IT">IT</option>
            <option value="Focení">Fotografování</option>
        </select><br>

        <label for="description">Co nejlépe popište, co budete vyučovat</label><br>
        <textarea name="description" id="" cols="100" rows="5"></textarea><br>

        <input type="submit" class="btn btn-success" value="Vytvořit">
    </form>
</div>