<div class="container">
    <form method="POST">
        <label for="heading">Zadejte nadpis</label><br>
        <input type="text" name="heading" id=""><br>

        <label for="description">Popište, koho hledáte a co byste se chtěl(a) naučit</label><br>
        <textarea name="description" id="" cols="100" rows="5"></textarea><br>

        <input type="submit" class="btn btn-success" value="Vytvořit">
    </form>
</div>