<section id="about">
    <div class="jumbotron jumbotron-fluid">
        <div class="container">
            <h1 class="display-4">Nauč se windsurfing.</h1>
            <p class="lead"></p>
        </div>
    </div>
</section>

<section class="container">
    <div class="row">
        <div class="col-md">
            <div class="card" style="width: 30rem;">
                <div class="card-body">
                    <h5 class="card-title">Václav Richter</h5>
                    <h6 class="card-subtitle mb-2 text-muted">Fitness</h6>
                    <p class="card-text">Vytvořím vám jídelníček a cvičební plán na míru</p>
                    <button id="basic-btn">Zobrazit</button>
                </div>
            </div>
        </div>
        <div class="col-md">
            <div class="card" style="width: 30rem;">
                <div class="card-body">
                    <h5 class="card-title">Karel Omáčka</h5>
                    <h6 class="card-subtitle mb-2 text-muted">Programování</h6>
                    <p class="card-text">Nabízím kurzy programování webových aplikací.</p>
                    <button id="basic-btn">Zobrazit</button>
                </div>
            </div>
        </div>
    </div>
    <div class="row">
        <div class="col-md">
            <div class="card" style="width: 30rem;">
                <div class="card-body">
                    <h5 class="card-title">Pavel Novák</h5>
                    <h6 class="card-subtitle mb-2 text-muted">Windsurfing</h6>
                    <p class="card-text">Nabízím výuku windsurfing pro začátečníky i mírně pokročilé.</p>
                    <button id="basic-btn">Zobrazit</button>
                </div>
            </div>
        </div>

        <div class="col-md">
            <div class="card" style="width: 30rem;">
                <div class="card-body">
                    <h5 class="card-title">Jana Zadinová</h5>
                    <h6 class="card-subtitle mb-2 text-muted">Vaření</h6>
                    <p class="card-text">Naučím vás výborně vařit. Mám 6 let zkušeností v gastronomii.</p>
                    <button id="basic-btn">Zobrazit</button>
                </div>
            </div>
        </div>
    </div>

    </div>
</section>
