<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Nauč.to</title>
    <link rel="stylesheet" href="style.css">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css"
          integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
</head>

<body>
<header>
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <a class="navbar-brand" href="<?=HOME_PATH?>"><b>Nauč.to</b></a>
        <div class="navbar-collapse">
            <div class="navbar-nav">
                <a class="nav-item nav-link js-scroll-trigger" href="#about">O nás</a>
                <a class="nav-item nav-link js-scroll-trigger" href="<?=HOME_PATH?>/demand/list">poptávky</a>
                <a class="nav-item nav-link js-scroll-trigger" href="<?=HOME_PATH?>/messages">zprávy</a>
                <a class="nav-item nav-link js-scroll-trigger" href="<?=HOME_PATH?>/offer/new">vytvořit nabídku</a>
                <a class="nav-item nav-link js-scroll-trigger" href="<?=HOME_PATH?>/demand/new">vytvořit poptávku</a>
                <a class="nav-item nav-link js-scroll-trigger" href="<?=HOME_PATH?>/offer/my-listing">moje nabídky</a>
                <a class="nav-item nav-link js-scroll-trigger" href="<?=HOME_PATH?>/demand/my-listing">moje poptávky</a>
            </div>
            <div class="ml-auto">
                <?php if (isset($_SESSION["loggedIn"])): ?>
                    <p>přihlášen - <?=$_SESSION["firstName"]?></p>
                    <a href="<?=HOME_PATH?>/user/logout">odhlásit se</a>
                <?php else: ?>
                    <a class="btn btn-primary text-right" href="<?=HOME_PATH?>/user/login">Přihlásit se</a>
                    <a class="btn btn-warning" href="<?=HOME_PATH?>/user/registration">Registrovat</a>
                <?php endif; ?>
            </div>
        </div>
    </nav>
</header>

<?php $this->controller->render() ?>

<footer>
    <div class="navbar bg-light">© 2020 Petr Netušil</div>
</footer>
</body>

</html>