<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Nauč se</title>
    <link rel="stylesheet" href="style.css">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
</head>

<body>
    <header>
        <nav class="navbar navbar-expand-lg navbar-light bg-light">
            <a class="navbar-brand" href="/apps/skola/php51/"><b>Nauč se</b></a>
            <div class="navbar-collapse">
                <div class="navbar-nav">
                    <a class="nav-item nav-link js-scroll-trigger" href="#about">O nás</a>
                </div>
                <div class="ml-auto">
                    <a class="btn btn-primary text-right" href="/apps/skola/php51/user/login">Login</a>
                    <a class="btn btn-warning" href="/apps/skola/php51/user/register">Register</a>
                </div>
            </div>
        </nav>
    </header>

    <?php $this->controller->render() ?>

    <footer>
        <div class="navbar bg-light">© 2020 Petr Netušil</div>
    </footer>
</body>

</html>