<div class="container">
    <h3 class="mt-4">Login</h3>
    <form method="POST">
        <div class="form-group">
            <label for="login">Login</label>
            <input type="text" class="form-control" placeholder="login" name="login">
            <label for="password">Password</label>
            <input type="password" class="form-control" placeholder="password" name="password">
        </div>

        <button type="submit" name="odeslat" class="btn btn-success mb-5">login</button><br>
    </form>
</div>