<div class="container">
    <h3 class="mt-4">Přihlásit se</h3>
    <form method="POST">
        <div class="form-group">
            <label for="email">E-mail</label>
            <input type="text" class="form-control" name="email">
            <label for="password">Heslo</label>
            <input type="password" class="form-control"  name="password">
        </div>

        <button type="submit" name="submit" class="btn btn-success mb-5">Přihlásit se</button><br>
    </form>
</div>