<div class="container mt-3 mb-3">
    <h3 class="mb-3">Zprávy</h3>
    <div>
        <div class="card">
            <div class="card-body">
                <h5 class="card-title">Václav Pavlíček</h5>
                <p>Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Aliquam erat volutpat. Praesent id justo in neque elementum ultrices. <a href="<?= HOME_PATH ?>/messages/1">zobrazit</a></p>
            </div>
        </div>
    </div>
    <div>
        <div class="card">
            <div class="card-body">
                <h5 class="card-title">Miroslav Bleha</h5>
                <p>Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Aliquam erat volutpat. Praesent id justo in neque elementum ultrices. <a href="<?= HOME_PATH ?>/messages/1">zobrazit</a></p>
            </div>
        </div>
    </div>
    <div>
        <div class="card">
            <div class="card-body">
                <h5 class="card-title">Radek Poláček</h5>
                <p>Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Aliquam erat volutpat. Praesent id justo in neque elementum ultrices. <a href="<?= HOME_PATH ?>/messages/1">zobrazit</a></p>
            </div>
        </div>
    </div>
    <div>
        <div class="card">
            <div class="card-body">
                <h5 class="card-title">Marie Krupková</h5>
                <p>Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Aliquam erat volutpat. Praesent id justo in neque elementum ultrices. <a href="<?= HOME_PATH ?>/messages/1">zobrazit</a></p>
            </div>
        </div>
    </div>
</div>