<div class="container">
    <h2>Windsurfing</h2>
    <p><b>Karel Omáčka</b></p>
    <p>Kategorie: sport</p>
    <p>Lokace: Pardubice</p>
    <img src="">
    <p>Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Aliquam erat volutpat. Praesent id justo in neque elementum ultrices. Phasellus enim erat,
    vestibulum vel, aliquam a, posuere eu, velit. Temporibus autem quibusdam et aut officiis debitis aut rerum necessitatibus saepe eveniet ut et voluptates
     repudiandae sint et molestiae non recusandae. Nemo enim ipsam voluptatem quia voluptas sit aspernatur</p>
    <h4>Hodnocení</h4>
    
     <form method="post">
         <textarea name="text" placeholder="napište zprávu" id="" cols="100" rows="5"></textarea><br>
         <input type="submit" class="btn btn-success" value="Odeslat">
     </form>
</div>