<div class="container">
    <h3 class="mt-4">Registrovat se</h3>
    <form method="POST">
        <div class="form-group">
            <label for="firstName">Křestní jméno</label>
            <input type="text" class="form-control" name="firstName">

            <label for="email">E-mail</label>
            <input type="text" class="form-control" name="email">
            <?php if (isset($emailEx)) : ?>
                <?= $emailEx ?><br>
            <?php endif ?>

            <label for="password">Heslo</label>
            <input type="password" class="form-control" name="password">
            <?php if (isset($passwordEx)) : ?>
                <?= $passwordEx ?><br>
            <?php endif ?>

            <label for="passwordAgain">Heslo znovu</label>
            <input type="password" class="form-control" name="passwordAgain">
            <?php if (isset($passwordAgainEx)) : ?>
                <?= $passwordAgainEx ?><br>
            <?php endif ?>

            <input type="checkbox" name="conditions">
            <label for="conditions">Souhlasím s obchodními podmínkami</label>
            <?php if (isset($conditionsEx)) : ?>
                <br><?= $conditionsEx ?><br>
            <?php endif ?>
        </div>
        <button type="submit" name="submit" class="btn btn-success mb-5">Registrovat</button><br>
    </form>
</div>