<div class="container">
    <h3 class="mt-4">Sign up</h3>
    <form method="POST">
        <div class="form-group">
            <label for="name">First name</label>
            <input type="text" class="form-control" name="name">

            <label for="email">Email</label>
            <input type="text" class="form-control" name="email">
            <?php if (isset($emailEx)) : ?>
                <?= $emailEx ?><br>
            <?php endif ?>

            <label for="password">Password</label>
            <input type="password" class="form-control" name="password">
            <?php if (isset($passwordEx)) : ?>
                <?= $passwordEx ?><br>
            <?php endif ?>

            <input type="checkbox" name="conditions">
            <label for="conditions">I agree with terms and conditions</label>
            <?php if (isset($conditonsEx)) : ?>
                <br><?= $conditionsEx ?><br>
            <?php endif ?>
        </div>
        <button type="submit" name="submit" class="btn btn-success mb-5">Register</button><br>
    </form>
</div>